// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/movies.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          string                 `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_movies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_movies_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type MovieIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieIdRequest) Reset() {
	*x = MovieIdRequest{}
	mi := &file_proto_movies_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieIdRequest) ProtoMessage() {}

func (x *MovieIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movies_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieIdRequest.ProtoReflect.Descriptor instead.
func (*MovieIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_movies_proto_rawDescGZIP(), []int{1}
}

func (x *MovieIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	mi := &file_proto_movies_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movies_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_movies_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoviesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMoviesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MovieListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	More          bool                   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieListResponse) Reset() {
	*x = MovieListResponse{}
	mi := &file_proto_movies_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieListResponse) ProtoMessage() {}

func (x *MovieListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movies_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieListResponse.ProtoReflect.Descriptor instead.
func (*MovieListResponse) Descriptor() ([]byte, []int) {
	return file_proto_movies_proto_rawDescGZIP(), []int{3}
}

func (x *MovieListResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *MovieListResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

func (x *MovieListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *MovieListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_movies_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movies_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_movies_proto_rawDescGZIP(), []int{4}
}

var File_proto_movies_proto protoreflect.FileDescriptor

const file_proto_movies_proto_rawDesc = "" +
	"\n" +
	"\x12proto/movies.proto\x12\x06movies\"A\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\tR\x04year\" \n" +
	"\x0eMovieIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"<\n" +
	"\x10GetMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"x\n" +
	"\x11MovieListResponse\x12%\n" +
	"\x06movies\x18\x01 \x03(\v2\r.movies.MovieR\x06movies\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\a\n" +
	"\x05Empty2\xe6\x01\n" +
	"\fMovieService\x121\n" +
	"\bGetMovie\x12\x16.movies.MovieIdRequest\x1a\r.movies.Movie\x12@\n" +
	"\tGetMovies\x12\x18.movies.GetMoviesRequest\x1a\x19.movies.MovieListResponse\x12+\n" +
	"\vCreateMovie\x12\r.movies.Movie\x1a\r.movies.Movie\x124\n" +
	"\vDeleteMovie\x12\x16.movies.MovieIdRequest\x1a\r.movies.EmptyB\tZ\a./protob\x06proto3"

var (
	file_proto_movies_proto_rawDescOnce sync.Once
	file_proto_movies_proto_rawDescData []byte
)

func file_proto_movies_proto_rawDescGZIP() []byte {
	file_proto_movies_proto_rawDescOnce.Do(func() {
		file_proto_movies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_movies_proto_rawDesc), len(file_proto_movies_proto_rawDesc)))
	})
	return file_proto_movies_proto_rawDescData
}

var file_proto_movies_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_movies_proto_goTypes = []any{
	(*Movie)(nil),             // 0: movies.Movie
	(*MovieIdRequest)(nil),    // 1: movies.MovieIdRequest
	(*GetMoviesRequest)(nil),  // 2: movies.GetMoviesRequest
	(*MovieListResponse)(nil), // 3: movies.MovieListResponse
	(*Empty)(nil),             // 4: movies.Empty
}
var file_proto_movies_proto_depIdxs = []int32{
	0, // 0: movies.MovieListResponse.movies:type_name -> movies.Movie
	1, // 1: movies.MovieService.GetMovie:input_type -> movies.MovieIdRequest
	2, // 2: movies.MovieService.GetMovies:input_type -> movies.GetMoviesRequest
	0, // 3: movies.MovieService.CreateMovie:input_type -> movies.Movie
	1, // 4: movies.MovieService.DeleteMovie:input_type -> movies.MovieIdRequest
	0, // 5: movies.MovieService.GetMovie:output_type -> movies.Movie
	3, // 6: movies.MovieService.GetMovies:output_type -> movies.MovieListResponse
	0, // 7: movies.MovieService.CreateMovie:output_type -> movies.Movie
	4, // 8: movies.MovieService.DeleteMovie:output_type -> movies.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_movies_proto_init() }
func file_proto_movies_proto_init() {
	if File_proto_movies_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_movies_proto_rawDesc), len(file_proto_movies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movies_proto_goTypes,
		DependencyIndexes: file_proto_movies_proto_depIdxs,
		MessageInfos:      file_proto_movies_proto_msgTypes,
	}.Build()
	File_proto_movies_proto = out.File
	file_proto_movies_proto_goTypes = nil
	file_proto_movies_proto_depIdxs = nil
}
